# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 azurerm: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 executor: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[Mapping[str, Any]] azurerm: provider configuration for azurerm
        :param pulumi.Input[_builtins.str] executor: Sets the executor used to run the module.
        """
        if azurerm is not None:
            pulumi.set(__self__, "azurerm", azurerm)
        if executor is None:
            executor = (_utilities.get_env('PULUMI_TERRAFORM_MODULE_EXECUTOR') or '')
        if executor is not None:
            pulumi.set(__self__, "executor", executor)

    @_builtins.property
    @pulumi.getter
    def azurerm(self) -> Optional[pulumi.Input[Mapping[str, Any]]]:
        """
        provider configuration for azurerm
        """
        return pulumi.get(self, "azurerm")

    @azurerm.setter
    def azurerm(self, value: Optional[pulumi.Input[Mapping[str, Any]]]):
        pulumi.set(self, "azurerm", value)

    @_builtins.property
    @pulumi.getter
    def executor(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Sets the executor used to run the module.
        """
        return pulumi.get(self, "executor")

    @executor.setter
    def executor(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "executor", value)


@pulumi.type_token("pulumi:providers:app_cluster")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 azurerm: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 executor: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a App_cluster resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, Any]] azurerm: provider configuration for azurerm
        :param pulumi.Input[_builtins.str] executor: Sets the executor used to run the module.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a App_cluster resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 azurerm: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 executor: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["azurerm"] = pulumi.Output.from_input(azurerm).apply(pulumi.runtime.to_json) if azurerm is not None else None
            if executor is None:
                executor = (_utilities.get_env('PULUMI_TERRAFORM_MODULE_EXECUTOR') or '')
            __props__.__dict__["executor"] = executor
        super(Provider, __self__).__init__(
            'app_cluster',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

