# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .module import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "demo_network",
  "mod": "index",
  "fqn": "pulumi_demo_network",
  "classes": {
   "demo_network:index:Module": "Module"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "demo_network",
  "token": "pulumi:providers:demo_network",
  "fqn": "pulumi_demo_network",
  "class": "Provider"
 }
]
"""
)
