# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ModuleArgs', 'Module']

@pulumi.input_type
class ModuleArgs:
    def __init__(__self__, *,
                 app_name: pulumi.Input[_builtins.str],
                 delegated_subnet_id: pulumi.Input[_builtins.str],
                 environment: pulumi.Input[_builtins.str],
                 private_dns_zone_id: pulumi.Input[_builtins.str],
                 resource_group_name: pulumi.Input[_builtins.str],
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 postgresql_version: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_name: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_mb: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a Module resource.

        :param pulumi.Input[_builtins.str] delegated_subnet_id: Subnet delegated to PostgreSQL Flexible Server by the network team
        :param pulumi.Input[_builtins.str] private_dns_zone_id: Private DNS zone for PostgreSQL — provisioned by the network team
        """
        pulumi.set(__self__, "app_name", app_name)
        pulumi.set(__self__, "delegated_subnet_id", delegated_subnet_id)
        pulumi.set(__self__, "environment", environment)
        pulumi.set(__self__, "private_dns_zone_id", private_dns_zone_id)
        pulumi.set(__self__, "resource_group_name", resource_group_name)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if postgresql_version is not None:
            pulumi.set(__self__, "postgresql_version", postgresql_version)
        if sku_name is not None:
            pulumi.set(__self__, "sku_name", sku_name)
        if storage_mb is not None:
            pulumi.set(__self__, "storage_mb", storage_mb)

    @_builtins.property
    @pulumi.getter
    def app_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "app_name")

    @app_name.setter
    def app_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "app_name", value)

    @_builtins.property
    @pulumi.getter
    def delegated_subnet_id(self) -> pulumi.Input[_builtins.str]:
        """
        Subnet delegated to PostgreSQL Flexible Server by the network team
        """
        return pulumi.get(self, "delegated_subnet_id")

    @delegated_subnet_id.setter
    def delegated_subnet_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "delegated_subnet_id", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter
    def private_dns_zone_id(self) -> pulumi.Input[_builtins.str]:
        """
        Private DNS zone for PostgreSQL — provisioned by the network team
        """
        return pulumi.get(self, "private_dns_zone_id")

    @private_dns_zone_id.setter
    def private_dns_zone_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "private_dns_zone_id", value)

    @_builtins.property
    @pulumi.getter
    def resource_group_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "resource_group_name")

    @resource_group_name.setter
    def resource_group_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "resource_group_name", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def postgresql_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "postgresql_version")

    @postgresql_version.setter
    def postgresql_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "postgresql_version", value)

    @_builtins.property
    @pulumi.getter
    def sku_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "sku_name")

    @sku_name.setter
    def sku_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "sku_name", value)

    @_builtins.property
    @pulumi.getter
    def storage_mb(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "storage_mb")

    @storage_mb.setter
    def storage_mb(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "storage_mb", value)


@pulumi.type_token("app_database:index:Module")
class Module(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: Optional[pulumi.Input[_builtins.str]] = None,
                 delegated_subnet_id: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 postgresql_version: Optional[pulumi.Input[_builtins.str]] = None,
                 private_dns_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 resource_group_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_name: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_mb: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a Module resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] delegated_subnet_id: Subnet delegated to PostgreSQL Flexible Server by the network team
        :param pulumi.Input[_builtins.str] private_dns_zone_id: Private DNS zone for PostgreSQL — provisioned by the network team
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ModuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Module resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ModuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ModuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: Optional[pulumi.Input[_builtins.str]] = None,
                 delegated_subnet_id: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 postgresql_version: Optional[pulumi.Input[_builtins.str]] = None,
                 private_dns_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 resource_group_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_name: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_mb: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ModuleArgs.__new__(ModuleArgs)

            if app_name is None and not opts.urn:
                raise TypeError("Missing required property 'app_name'")
            __props__.__dict__["app_name"] = app_name
            if delegated_subnet_id is None and not opts.urn:
                raise TypeError("Missing required property 'delegated_subnet_id'")
            __props__.__dict__["delegated_subnet_id"] = delegated_subnet_id
            if environment is None and not opts.urn:
                raise TypeError("Missing required property 'environment'")
            __props__.__dict__["environment"] = environment
            __props__.__dict__["location"] = location
            __props__.__dict__["postgresql_version"] = postgresql_version
            if private_dns_zone_id is None and not opts.urn:
                raise TypeError("Missing required property 'private_dns_zone_id'")
            __props__.__dict__["private_dns_zone_id"] = private_dns_zone_id
            if resource_group_name is None and not opts.urn:
                raise TypeError("Missing required property 'resource_group_name'")
            __props__.__dict__["resource_group_name"] = resource_group_name
            __props__.__dict__["sku_name"] = sku_name
            __props__.__dict__["storage_mb"] = storage_mb
            __props__.__dict__["db_fqdn"] = None
            __props__.__dict__["db_name"] = None
            __props__.__dict__["db_port"] = None
            __props__.__dict__["db_username"] = None
        super(Module, __self__).__init__(
            'app_database:index:Module',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Module':
        """
        Get an existing Module resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ModuleArgs.__new__(ModuleArgs)

        __props__.__dict__["db_fqdn"] = None
        __props__.__dict__["db_name"] = None
        __props__.__dict__["db_port"] = None
        __props__.__dict__["db_username"] = None
        return Module(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def db_fqdn(self) -> pulumi.Output[Optional[Any]]:
        return pulumi.get(self, "db_fqdn")

    @_builtins.property
    @pulumi.getter
    def db_name(self) -> pulumi.Output[Optional[Any]]:
        return pulumi.get(self, "db_name")

    @_builtins.property
    @pulumi.getter
    def db_port(self) -> pulumi.Output[Optional[Any]]:
        return pulumi.get(self, "db_port")

    @_builtins.property
    @pulumi.getter
    def db_username(self) -> pulumi.Output[Optional[Any]]:
        return pulumi.get(self, "db_username")

